import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Maverick Silk Shirt',
    price: 180,
    image: 'https://placehold.co/600x800',
    imageHint: 'silk shirt',
    category: 'Men',
    description: 'A luxurious silk shirt with a classic collar and a modern fit. Perfect for any occasion.',
  },
  {
    id: 'p2',
    name: 'Elegance Trench Coat',
    price: 450,
    image: 'https://placehold.co/600x800',
    imageHint: 'trench coat',
    category: 'Women',
    description: 'A timeless trench coat crafted from water-resistant cotton gabardine. Features a double-breasted closure and a belted waist.',
  },
  {
    id: 'p3',
    name: 'Apex Leather Jacket',
    price: 620,
    image: 'https://placehold.co/600x800',
    imageHint: 'leather jacket',
    category: 'Unisex',
    description: 'A statement leather jacket made from premium lambskin. Designed for a bold, contemporary look.',
  },
  {
    id: 'p4',
    name: 'Nomad Cashmere Scarf',
    price: 120,
    image: 'https://placehold.co/600x800',
    imageHint: 'cashmere scarf',
    category: 'Accessories',
    description: 'An ultra-soft cashmere scarf, perfect for adding a touch of luxury and warmth to your outfit.',
  },
  {
    id: 'p5',
    name: 'Metropolis Linen Trousers',
    price: 210,
    image: 'https://placehold.co/600x800',
    imageHint: 'linen trousers',
    category: 'Men',
    description: 'Lightweight and breathable linen trousers with a tailored fit. Ideal for warm weather and sophisticated style.',
  },
  {
    id: 'p6',
    name: 'Aura Satin Blouse',
    price: 165,
    image: 'https://placehold.co/600x800',
    imageHint: 'satin blouse',
    category: 'Women',
    description: 'A fluid satin blouse with a delicate neckline and flowing sleeves. A versatile piece for day or night.',
  },
  {
    id: 'p7',
    name: 'Vertex Wool Sweater',
    price: 250,
    image: 'https://placehold.co/600x800',
    imageHint: 'wool sweater',
    category: 'Unisex',
    description: 'A minimalist wool sweater crafted from fine merino wool. Soft, warm, and endlessly versatile.',
  },
  {
    id: 'p8',
    name: 'Solstice Gold Hoops',
    price: 95,
    image: 'https://placehold.co/600x800',
    imageHint: 'gold earrings',
    category: 'Accessories',
    description: 'Classic gold hoop earrings with a modern, lightweight design. Plated in 18k gold.',
  },
];
