import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: '21st SM Hoodie',
    price: 250,
    image: 'https://i.postimg.cc/J7yDFdw7/21st-sm-hoodie-png.jpg',
    imageHint: 'black hoodie',
    category: 'Hoodies',
    description: 'A comfortable and stylish hoodie featuring the 21st SM design.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p2',
    name: 'Triple Cross Hoodie',
    price: 250,
    image: 'https://placehold.co/600x800.png',
    imageHint: 'graphic hoodie',
    category: 'Hoodies',
    description: 'A premium hoodie with the iconic Triple Cross design.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p3',
    name: '21st SM Sweatshirt',
    price: 200,
    image: 'https://i.postimg.cc/g0qqntcb/21-sm-sweatshirt.jpg',
    imageHint: 'crewneck sweatshirt',
    category: 'Sweatshirts',
    description: 'A classic sweatshirt with the 21st SM logo, perfect for a casual look.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p4',
    name: 'Triple Cross Sweatshirt',
    price: 200,
    image: 'https://i.postimg.cc/RFJtwP40/triple-cross-sweatshirt.jpg',
    imageHint: 'designer sweatshirt',
    category: 'Sweatshirts',
    description: 'Showcase your style with the Triple Cross sweatshirt.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p5',
    name: '21st SM Shirt',
    price: 180,
    image: 'https://placehold.co/600x800.png',
    imageHint: 'cotton t-shirt',
    category: 'Cotton T-Shirts',
    description: 'A high-quality cotton t-shirt with the 21st SM print.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p6',
    name: 'Triple Cross Shirt',
    price: 180,
    image: 'https://placehold.co/600x800.png',
    imageHint: 'graphic t-shirt',
    category: 'Cotton T-Shirts',
    description: 'A bold statement t-shirt with the Triple Cross design.',
    colors: ['White', 'Blue', 'Black', 'Blue-black', 'Pink', 'Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'p9',
    name: 'SM Crop Tees',
    price: 200,
    image: 'https://i.postimg.cc/7Zp9dThb/sm-crop-tee.jpg',
    imageHint: 'crop top',
    category: 'Croptop',
    description: 'A trendy and comfortable crop tee for a stylish look.',
    colors: ['Pink', 'White', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
];
